### ISSUE TITLE
Paypal Gem raises method_missing error in production

### ISSUE THREAD

**Issue by kikrahau** [paypal/PayPal-Ruby-SDK#117]
After pushing to production, I received the following error. In development everything works fine.
I can't get it running. Anyone knows how to fix it? Help is very much appreciated!

config/initializers/paypal.rb
----

```
if Rails.env.production?
  PAYPALMODE = 'live'
  PAYPALCLIENTID = ENV['PAYPAL_LIVE_CLIENT_ID']
  PAYPALCLIENTSECRET = ENV['PAYPAL_LIVE_CLIENT_SECRET']
else
  PAYPALMODE = 'sandbox'
  PAYPALCLIENTID = ENV['PAYPAL_SANDBOX_CLIENT_ID']
  PAYPALCLIENTSECRET = ENV['PAYPAL_SANDBOX_CLIENT_SECRET']
end

PayPal::SDK::REST.set_config(
    :mode => PAYPALMODE,
    :client_id =>  PAYPALCLIENTID,
    :client_secret => PAYPALCLIENTSECRET,
    :app_id => 'APP-ID',
    :username => ENV['PAYPAL_API_USERNAME'],
    :password => ENV['PAYPAL_API_PASSWORD'],
    :signature => ENV['PAYPAL_API_SIGNATURE'],
)

PayPal::SDK.logger = Rails.logger
```
Stack trace:
----
```
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.1/lib/paypal-sdk/rest.rb:19:in `method_missing'
from xxx/apps/2wunder-v3/production/config/initializers/paypal.rb:11:in `<top (required)>'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
 from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
        from xxx/apps/2wunder-v3/production/config/environment.rb:32:in `<top (required)>'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:67:in `console'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'

**Comment by jziaja** [comment]
Hi @kikrahau , try changing line 11 in your script to the following:

````ruby
PayPal::SDK::Core::Config.set_config(
````

Also, I noticed you're using version 1.1.1.  You may want to upgrade to the latest version **1.1.3** as it fixes a few bugs that were present in the previous versions.

**Comment by kikrahau** [comment]
Updated the gem and replaced the line as you suggested, but I still a similar error. Slightly different now
```
        from /xxx/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.1.3/lib/paypal-sdk/core/config.rb:178:in `configure'
        from /xxx/apps/2wunder-v3/production/config/initializers/paypal.rb:11:in `<top (required)>'

**Comment by kikrahau** [comment]
As it turned out (as so often), it had nothing to do with the gem itself, but with a wrong defined variable somewhere else. I still don't know, why it raised such an error. Thanks for your help though!

**Comment by jziaja** [comment]
Interesting, and glad you got it figured out!  Just curious, but was the wrongly defined variable something related to the SDK?  If so, we'd love to know what it was so we can provide better documentation on how to correctly use the SDK.

(_Closing this issue since the problem was resolved._)
