### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by jcdavison** [paypal/PayPal-Ruby-SDK#144]
Using a pretty typical `Payment.create({args})` and `Payment.execute({})` flow, I'm receiving a `java.lang.NullPointerException` which of course, I'm pretty unclear on.

Thoughts? 

Full stack trace.

```
irb(main):041:0> c.execute(payer_id: "KLR8BRB4T2DCN")
PayPal-Request-Id: 7fd56259-fb48-4a40-bdad-46dfc5b48f45
Request[post]: https://api.sandbox.paypal.com/v1/payments/payment//execute
Request.body={"payer_id":"KLR8BRB4T2DCN"}	request.header={"Authorization"=>"Bearer A015SZ1oM-vYu6fQPnSDCEccH9p48eFBxTJGjwOJyvO.nNE", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.3.2 (paypal-sdk-core 1.3.2; ruby 2.2.2p95-x86_64-darwin14)", "PayPal-Request-Id"=>"7fd56259-fb48-4a40-bdad-46dfc5b48f45"}
Response[500]: Internal Server Error, Duration: 0.958s
Response.body: <ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">java.lang.NullPointerException</ns1:faultstring></ns1:XMLFault>
PayPal::SDK::Core::Exceptions::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/core/util/http_helper.rb:153:in `handle_response'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/core/api/rest.rb:110:in `handle_response'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/core/util/http_helper.rb:85:in `http_call'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/core/api/base.rb:86:in `api_call'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/core/api/rest.rb:95:in `api_call'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/core/api/base.rb:98:in `post'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/paypal-sdk-rest-1.3.2/lib/paypal-sdk/rest/data_types.rb:80:in `execute'
	from (irb):41
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/console.rb:110:in `start'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/console.rb:9:in `start'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /Users/sens/propeller-code/wineapp/bin/rails:8:in `<top (required)>'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sens/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'irb(main):042:0>
```

**Comment by jziaja** [comment]
@jcdavison, try changing `payer_id` to `id` in your call: 

````ruby
c.execute(id: "KLR8BRB4T2DCN")
````

**Comment by jziaja** [comment]
Whoops, ignore my previous suggestion...  Give me just a bit. :)

**Comment by jziaja** [comment]
@jcdavison, can you share how you're setting up the payment object prior to calling `execute()`?  It looks like it's missing the `id` needed to generate the URL.

**Comment by jcdavison** [comment]
hey @jziaja thanks for the speedy response,

```ruby
p = PayPal::SDK::REST::Payment.new({id: "PAY-289401343F4509222KW34F7A"})
p.execute({payer_id: "KLR8BRB4T2DCN"})
```

Worked so the official docs, https://devtools-paypal.com/guide/pay_paypal/ruby?interactive=OFF&env=sandbox reference to `payment_id` might need to be changed as I noticed that throws and error, https://www.dropbox.com/s/bu8lah5x3ujkgbj/Screenshot%202015-07-28%2011.43.29.png?dl=0

https://www.dropbox.com/s/z74gb1xjyslrevt/Screenshot%202015-07-28%2011.42.54.png?dl=0

Seems like I'm good to go, thanks.

**Comment by jziaja** [comment]
Thanks for pointing that out, @jcdavison.  I'll notify the docs team that **Step 4 of 5** needs to be changed so it references `id` instead of `payment_id`.

**Comment by jcdavison** [comment]
:+1:

**Comment by dharabhaskar** [comment]
what is the payer_id

**Comment by pp-randy** [comment]
@dharabhaskar you can find details here: https://developer.paypal.com/docs/api/payments/#payment_execute_request

If you are getting an error please create a new issue and we will be happy to take a look.
