### ISSUE TITLE
1.4.2 broke merchant-sdk-ruby gem

### ISSUE THREAD

**Issue by ollym** [paypal/PayPal-Ruby-SDK#184]
```
[irb(main):003:0> PayPal::SDK::Merchant::API
NameError: uninitialized constant PayPal::SDK::Core::API::Merchant
	from /ruby/gems/2.3.0/gems/paypal-sdk-merchant-1.117.2/lib/paypal-sdk/merchant/api.rb:6:in `<module:Merchant>'
	from /ruby/gems/2.3.0/gems/paypal-sdk-merchant-1.117.2/lib/paypal-sdk/merchant/api.rb:5:in `<module:SDK>'
	from /ruby/gems/2.3.0/gems/paypal-sdk-merchant-1.117.2/lib/paypal-sdk/merchant/api.rb:4:in `<module:PayPal>'
	from /ruby/gems/2.3.0/gems/paypal-sdk-merchant-1.117.2/lib/paypal-sdk/merchant/api.rb:3:in `<top (required)>'
```

**Comment by bluk** [comment]
I reverted some changes which I believe should resolve this issue. It is released as version `1.4.3`. Thanks for the report.
