### ISSUE TITLE
Payment Capture Failure - PayPal-Debug-ID: 18d369fd5f4e6

### ISSUE THREAD

**Issue by AndrewPratley** [paypal/PayPal-Ruby-SDK#266]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): 18d369fd5f4e6
- Version of Ruby used: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
- SDK Version: paypal-sdk-rest (1.6.0)
      multi_json (~> 1.0)
      xml-simple

### Issue Description

A payment failed to capture and this is the response we received the response below. Can you tell me why this failed?

Exception
PayPal::SDK::Core::Exceptions::ServerError

Error
Failed. Response code = 500. Response message = Internal Server Error. Response debug ID = 18d369fd5f4e6, 18d369fd5f4e6.
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/util/http_helper.rb:153:in `handle_response'
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/rest.rb:111:in `handle_response'
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/util/http_helper.rb:78:in `http_call'
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/base.rb:86:in `api_call'
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/rest.rb:96:in `api_call'
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/base.rb:98:in `post'
/srv/www/bellroy-production/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/rest/data_types.rb:870:in `capture'

**Comment by pp-randy** [comment]
@AndrewPratley I apologize for the delay in response.  PayPal Merchant Technical Support would be able to better assist you with this Live capture error.  If the issue still persists you can submit a ticket here: https://www.paypal-techsupport.com/app/ask

**Comment by joseneto** [comment]
Ok, o dont see any debug id in my sandbox api call history, i can see only the url, but there is some debug id in my console.(I remove the currency_code)


```
Request[post]: https://api.sandbox.paypal.com/v1/oauth2/token
Request.body=grant_type=client_credentials	request.header={"User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.1 (paypal-sdk-core 1.6.1; ruby 2.2.0p0-x86_64-darwin15;OpenSSL 1.0.2k  26 Jan 2017)", "Content-Type"=>"application/x-www-form-urlencoded", "Authorization"=>"Basic QWVUMWJueEhjT2tENDh2eWRqdXZWRGJfUm1QNVQzdlFaWHlJbjJLenJQWXRIQXgyblBpVURnRktzVVNzNHlhZU5ZNzFuSkVpbVo3WnlDWWE6RUpNMjBpMF9ybDNHVDB3SmJzWDFHSW9zTkxjbGZvUk40Rl9ZY0t3dHZEX3hHb09rOWk5eGZPLURraVR3QUlEOTlYV1JQdkpJQThXTzUzZkI="}
Response[200]: OK, Duration: 1.492s
Response.body={"scope":"https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.*","nonce":"2017-10-28T18:13:46ZqhHxNlleTllCWWH6b2lyTHIr7wz5oMVQObPblPwD57g","access_token":"A21AAH4VdzGghbQ8pEFLAJFb6BhigBw7exrbxmH-w5RErWyJh_R5WTHLn3FID79DgKa5vIApm16I9oKflb5lgSdmTx00-PYBQ","token_type":"Bearer","app_id":"APP-80W284485P519543T","expires_in":32400}	Response.header={"date"=>["Sat, 28 Oct 2017 18:13:46 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["d32036e45b519", "d32036e45b519"], "x-paypal-token-service"=>["IAAS"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3670602841%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 28 Oct 2017 18:43:46 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["550"], "connection"=>["close"], "content-type"=>["application/json"]}
PayPal-Request-Id: 9b06a98f-da53-41cd-b84b-f75ac9bbedee
Request[post]: https://api.sandbox.paypal.com/v1/payments/billing-plans/
Request.body={"name":"T-Shirt of the Month Club Plan","description":"Template creation.","type":"fixed","payment_definitions":[{"name":"Regular Payments","type":"REGULAR","frequency_interval":"2","frequency":"MONTH","cycles":"12","amount":{"currency":"BRL","value":"100"}}],"merchant_preferences":{"setup_fee":{"currency":"BRL","value":"0"},"cancel_url":"http://localhost:3000/conta/cancelar","return_url":"http://localhost:3000/conta/retorno","max_fail_attempts":"0","auto_bill_amount":"YES","initial_fail_amount_action":"CONTINUE"}}	request.header={"Authorization"=>"Bearer A21AAH4VdzGghbQ8pEFLAJFb6BhigBw7exrbxmH-w5RErWyJh_R5WTHLn3FID79DgKa5vIApm16I9oKflb5lgSdmTx00-PYBQ", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.1 (paypal-sdk-core 1.6.1; ruby 2.2.0p0-x86_64-darwin15;OpenSSL 1.0.2k  26 Jan 2017)", "PayPal-Request-Id"=>"9b06a98f-da53-41cd-b84b-f75ac9bbedee"}
Response[201]: Created, Duration: 0.846s
Response.body={"id":"P-3GJ00288EX0445228MQYJUWY","state":"CREATED","name":"T-Shirt of the Month Club Plan","description":"Template creation.","type":"FIXED","payment_definitions":[{"id":"PD-2W970445727839942MQYJUWY","name":"Regular Payments","type":"REGULAR","frequency":"Month","amount":{"currency":"BRL","value":"100"},"cycles":"12","charge_models":[],"frequency_interval":"2"}],"merchant_preferences":{"setup_fee":{"currency":"BRL","value":"0"},"max_fail_attempts":"0","return_url":"http://localhost:3000/conta/retorno","cancel_url":"http://localhost:3000/conta/cancelar","auto_bill_amount":"YES","initial_fail_amount_action":"CONTINUE"},"create_time":"2017-10-28T18:13:47.739Z","update_time":"2017-10-28T18:13:47.739Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/billing-plans/P-3GJ00288EX0445228MQYJUWY","rel":"self","method":"GET"}]}	Response.header={"date"=>["Sat, 28 Oct 2017 18:13:47 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["349e2c07a776e", "349e2c07a776e"], "content-language"=>["*"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3687380057%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 28 Oct 2017 18:43:47 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["842"], "connection"=>["close"], "content-type"=>["application/json"]}
PayPal-Request-Id: 9b06a98f-da53-41cd-b84b-f75ac9bbedee
Request[patch]: https://api.sandbox.paypal.com/v1/payments/billing-plans/P-3GJ00288EX0445228MQYJUWY
Request.body=[{"op":"replace","path":"/","value":{"state":"ACTIVE"}}]	request.header={"Authorization"=>"Bearer A21AAH4VdzGghbQ8pEFLAJFb6BhigBw7exrbxmH-w5RErWyJh_R5WTHLn3FID79DgKa5vIApm16I9oKflb5lgSdmTx00-PYBQ", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.1 (paypal-sdk-core 1.6.1; ruby 2.2.0p0-x86_64-darwin15;OpenSSL 1.0.2k  26 Jan 2017)", "PayPal-Request-Id"=>"9b06a98f-da53-41cd-b84b-f75ac9bbedee"}
Response[200]: OK, Duration: 2.583s
Response.body=	Response.header={"date"=>["Sat, 28 Oct 2017 18:13:48 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["3f355bf67ba76", "3f355bf67ba76"], "content-language"=>["*"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3704157273%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 28 Oct 2017 18:43:50 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["0"], "connection"=>["close"], "content-type"=>["text/plain; charset=ISO-8859-1"]}
PayPal-Request-Id: 09177870-b9ce-47ad-a40f-5b269e2f8910
Request[post]: https://api.sandbox.paypal.com/v1/oauth2/token
Request.body=grant_type=client_credentials	request.header={"User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.1 (paypal-sdk-core 1.6.1; ruby 2.2.0p0-x86_64-darwin15;OpenSSL 1.0.2k  26 Jan 2017)", "Content-Type"=>"application/x-www-form-urlencoded", "Authorization"=>"Basic QWVUMWJueEhjT2tENDh2eWRqdXZWRGJfUm1QNVQzdlFaWHlJbjJLenJQWXRIQXgyblBpVURnRktzVVNzNHlhZU5ZNzFuSkVpbVo3WnlDWWE6RUpNMjBpMF9ybDNHVDB3SmJzWDFHSW9zTkxjbGZvUk40Rl9ZY0t3dHZEX3hHb09rOWk5eGZPLURraVR3QUlEOTlYV1JQdkpJQThXTzUzZkI=", "PayPal-Request-Id"=>"09177870-b9ce-47ad-a40f-5b269e2f8910"}
Response[200]: OK, Duration: 0.891s
Response.body={"scope":"https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.*","nonce":"2017-10-28T18:13:46ZqhHxNlleTllCWWH6b2lyTHIr7wz5oMVQObPblPwD57g","access_token":"A21AAH4VdzGghbQ8pEFLAJFb6BhigBw7exrbxmH-w5RErWyJh_R5WTHLn3FID79DgKa5vIApm16I9oKflb5lgSdmTx00-PYBQ","token_type":"Bearer","app_id":"APP-80W284485P519543T","expires_in":32395}	Response.header={"date"=>["Sat, 28 Oct 2017 18:13:51 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["5b46531a3c5c1", "5b46531a3c5c1"], "x-paypal-token-service"=>["IAAS"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3754488921%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 28 Oct 2017 18:43:51 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["550"], "connection"=>["close"], "content-type"=>["application/json"]}
PayPal-Request-Id: 09177870-b9ce-47ad-a40f-5b269e2f8910
Request[post]: https://api.sandbox.paypal.com/v1/payments/billing-agreements/
Request.body={"name":"T-Shirt of the Month Club Agreement","description":"Agreement for T-Shirt of the Month Club Plan","start_date":"2017-10-29T00:00:00-07:00","payer":{"payment_method":"paypal"},"plan":{"id":"P-3GJ00288EX0445228MQYJUWY"}}	request.header={"Authorization"=>"Bearer A21AAH4VdzGghbQ8pEFLAJFb6BhigBw7exrbxmH-w5RErWyJh_R5WTHLn3FID79DgKa5vIApm16I9oKflb5lgSdmTx00-PYBQ", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.1 (paypal-sdk-core 1.6.1; ruby 2.2.0p0-x86_64-darwin15;OpenSSL 1.0.2k  26 Jan 2017)", "PayPal-Request-Id"=>"09177870-b9ce-47ad-a40f-5b269e2f8910"}
Response[201]: Created, Duration: 14.088s
Response.body={"name":"T-Shirt of the Month Club Agreement","description":"Agreement for T-Shirt of the Month Club Plan","plan":{"id":"P-3GJ00288EX0445228MQYJUWY","state":"ACTIVE","name":"T-Shirt of the Month Club Plan","description":"Template creation.","type":"FIXED","payment_definitions":[{"id":"PD-2W970445727839942MQYJUWY","name":"Regular Payments","type":"REGULAR","frequency":"Month","amount":{"currency":"BRL","value":"100"},"cycles":"12","charge_models":[],"frequency_interval":"2"}],"merchant_preferences":{"setup_fee":{"currency":"BRL","value":"0"},"max_fail_attempts":"0","return_url":"http://localhost:3000/conta/retorno","cancel_url":"http://localhost:3000/conta/cancelar","auto_bill_amount":"YES","initial_fail_amount_action":"CONTINUE"}},"links":[{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-48425327CM870721E","rel":"approval_url","method":"REDIRECT"},{"href":"https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-48425327CM870721E/agreement-execute","rel":"execute","method":"POST"}],"start_date":"2017-10-29T00:00:00-07:00"}	Response.header={"date"=>["Sat, 28 Oct 2017 18:13:51 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["5e29b36522832", "5e29b36522832"], "content-language"=>["*"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3955815513%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 28 Oct 2017 18:44:05 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["1083"], "connection"=>["close"], "content-type"=>["application/json"]}

```

**Here is the console part after call the agreament**

```
{"token"=>"EC-48425327CM870721E", "controller"=>"conta", "action"=>"retorno"}
PayPal-Request-Id: f8247dd1-32b8-4476-9dcc-c101decf8636
Request[post]: https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-48425327CM870721E/agreement-execute
Request.body={}	request.header={"Authorization"=>"Bearer A21AAH4VdzGghbQ8pEFLAJFb6BhigBw7exrbxmH-w5RErWyJh_R5WTHLn3FID79DgKa5vIApm16I9oKflb5lgSdmTx00-PYBQ", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.6.1 (paypal-sdk-core 1.6.1; ruby 2.2.0p0-x86_64-darwin15;OpenSSL 1.0.2k  26 Jan 2017)", "PayPal-Request-Id"=>"f8247dd1-32b8-4476-9dcc-c101decf8636"}
Response[200]: OK, Duration: 5.838s
Response.body={"id":"I-UWG0F6LNJ5V2","state":"Active","description":"Agreement for T-Shirt of the Month Club Plan","payer":{"payment_method":"paypal","status":"verified","payer_info":{"email":"jmedeiros.neto-buyer@gmail.com","first_name":"test","last_name":"buyer","payer_id":"LNZ5GW57ZCW5W","shipping_address":{"recipient_name":"test buyer","line1":"1234 Rua Main","city":"Rio De Janeiro","state":"RJ","postal_code":"22021-001","country_code":"BR"}}},"plan":{"payment_definitions":[{"type":"REGULAR","frequency":"Month","amount":{"value":"100.00"},"cycles":"12","charge_models":[{"type":"TAX","amount":{"value":"0.00"}},{"type":"SHIPPING","amount":{"value":"0.00"}}],"frequency_interval":"2"}],"merchant_preferences":{"setup_fee":{"value":"0.00"},"max_fail_attempts":"0","auto_bill_amount":"YES"},"links":[],"currency_code":"BRL"},"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-UWG0F6LNJ5V2","rel":"self","method":"GET"}],"start_date":"2017-10-29T02:00:00Z","shipping_address":{"recipient_name":"test buyer","line1":"1234 Rua Main","city":"Rio De Janeiro","state":"RJ","postal_code":"22021-001","country_code":"BR"},"agreement_details":{"outstanding_balance":{"value":"0.00"},"cycles_remaining":"12","cycles_completed":"0","next_billing_date":"2017-10-29T10:00:00Z","final_payment_date":"2019-08-29T10:00:00Z","failed_payment_count":"0"}}	Response.header={"date"=>["Sat, 28 Oct 2017 18:14:54 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["e11d2eefa3b8f", "e11d2eefa3b8f"], "content-language"=>["*"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D516551769%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 28 Oct 2017 18:44:59 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["1360"], "connection"=>["close"], "content-type"=>["application/json"]}
undefined method `currency_code=' for #<PayPal::SDK::REST::DataTypes::Plan:0x007f8ddbea4ac8>
undefined method `recipient_name=' for #<PayPal::SDK::REST::DataTypes::Address:0x007f8ddbe9ec68>
```

**Comment by pp-randy** [comment]
@joseneto I'm not sure what your issue is your reporting.  It looks like you created a recurring billing agreement here: I-UWG0F6LNJ5V2.  Can you file a new issue and we will look further?   

The original issue is unrelated.
