### ISSUE TITLE
On INSUFFICIENT_FUNDS, Payout.new(...).create(true) fails to throw proper error

### ISSUE THREAD

**Issue by engshien** [paypal/PayPal-Ruby-SDK#298]
When calling
  `PayPal::SDK::REST::Payout.new(...).create(true)`
with insufficient funds, the PayPal SDK fails to throw a proper error but instead throws NameError
  `uninitialized constant PayPal::SDK::Core::Util::HTTPHelper::ResourceInvalid`

Here are the logs
```
Jul 14 20:46:10 W, [2017-07-14T20:46:10.668301 #30]  WARN -- : Response.body={"name":"INSUFFICIENT_FUNDS","message":"An internal service error has occurred.","debug_id":"c28e009e3f21b","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}        Response.header={"date"=>["Fri, 14 Jul 2017 20:46:10 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["c28e009e3f21b", "c28e009e3f21b"], "content-language"=>["*"], "set-cookie"=>["X-PP-SILOVER=...; Expires=Fri, 14 Jul 2017 21:16:10 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["198"], "cache-control"=>["max-age=0, no-cache, no-store, must-revalidate"], "pragma"=>["no-cache"], "connection"=>["close"], "content-type"=>["application/json"]}
Jul 14 20:46:10 {"severity": "ERROR", "datetime": "2017-07-14T20:46:10.668506+00:00", "progname": “...”, "message": {"ex_name":"NameError","ex_message":"uninitialized constant PayPal::SDK::Core::Util::HTTPHelper::ResourceInvalid","ex_backtrace":["/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/util/http_helper.rb:149:in `handle_response'","/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/rest.rb:111:in `handle_response'","/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/util/http_helper.rb:78:in `http_call'","/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/base.rb:86:in `api_call'","/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/rest.rb:96:in `api_call'","/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/core/api/base.rb:98:in `post'","/usr/src/app/vendor/bundle/ruby/2.4.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/rest/data_types.rb:1687:in `create’”,…}}
```

**Comment by pp-randy** [comment]
Thank you for reporting this issue the API response has been updated recently.  We will look into making any needed updates to the SDK.

**Comment by garcha** [comment]
@pp-randy did paypal make an update in regards to funds available in a sandboxes account? I'm also getting an 'INSUFFICIENT_FUNDS' error in sandbox.

However my research shows, this error shouldn't really be happening in sandbox.

**Comment by pp-randy** [comment]
`INSUFFICIENT_FUNDS` is returned when you do not have enough funds of the currency in the PayPal account.  Payouts use the PayPal balance.  The easy sandbox fix is to send your account some money from another or run some transactions.  Since I test regularly I also have some recurring payments set up to get money into my primary business account.

**Comment by pp-randy** [comment]
Closing this issue in favor of the pull request here should resolve it https://github.com/paypal/PayPal-Ruby-SDK/pull/300.
