### ISSUE TITLE
NoMethodError: undefined method `find' for PayPal::SDK::REST::RequestDataType:Module

### ISSUE THREAD

**Issue by heaven** [paypal/PayPal-Ruby-SDK#305]
Error when trying to retrieve Webhook Event

* SDK/Library version: 1.6.0
* Environment: Sandbox

```
2.3.0 :001 > include PayPal::SDK::REST
 => Object
2.3.0 :002 > include PayPal::SDK::Core::Logging
 => Object
2.3.0 :003 > WebhookEvent.get("WH-7Y7254563A4550640-11V2185806837105M")
NoMethodError: undefined method `find' for PayPal::SDK::REST::RequestDataType:Module
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/rest.rb:19:in `method_missing'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/paypal-sdk-rest-1.6.0/lib/paypal-sdk/rest/data_types.rb:1594:in `get'
	from (irb):3
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/www/crm.wegohealth.com/shared/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:10:in `require'
	from bin/rails:10:in `<main>'
```

**Comment by heaven** [comment]
Here https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/rest/data_types.rb#L1597 class methods wrapped in `class << self` twice.

**Comment by pp-randy** [comment]
Closing the issue, will use your pull request to track. Thank you for the pull.

**Comment by pp-randy** [comment]
https://github.com/paypal/PayPal-Ruby-SDK/pull/306
