### ISSUE TITLE
Agreement issue in v0.10.0

### ISSUE THREAD

**Issue by yoonwaiyan** [paypal/PayPal-Ruby-SDK#76]
Was testing the new release on this gem by trying out the set balance function of Paypal Agreement but I've received an internal server error on this. This is a new agreement so there's no outstanding balance at the moment.

```ruby
bill = Paypal::Agreement.find("I-MYNYLVTWTYU2")
bill.set_balance({
  value: "10.00",
  currency: "USD"
})
```

```
PayPal-Request-Id: 0feb8b50-1dcc-47da-a388-222b47ed08cd
Request[post]: https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-MYNYLVTWTYU2/set-balance
Response[500]: Internal Server Error, Duration: 3.461s
PayPal::SDK::Core::Exceptions::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = 986eaf447ced6.
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/util/http_helper.rb:151:in `handle_response'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/rest.rb:110:in `handle_response'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/util/http_helper.rb:85:in `http_call'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/base.rb:84:in `api_call'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/rest.rb:95:in `api_call'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-core-0.3.1/lib/paypal-sdk/core/api/base.rb:96:in `post'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/paypal-sdk-rest-0.10.0/lib/paypal-sdk/rest/data_types.rb:1414:in `set_balance'
	from (irb):51
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by juwlee** [comment]
@yoonwaiyan can you please try again and share the debug ID? Also, it would help if the retrieved agreement (ID: I-MYNYLVTWTYU2) is posted here.

**Comment by juwlee** [comment]
Closing for now. Please re-open with a debug ID and the retrieved agreement so that I can look deeper into it.
