### ISSUE TITLE
Payment.new generates OpenSSL::SSL::SSLError (certificate verify failed)

### ISSUE THREAD

**Issue by trantorLiu** [paypal/PayPal-Ruby-SDK#90]
I have got `OpenSSL::SSL::SSLError`s since 1/28/2015. Before that day, it worked fine. I then updated this gem, which didn't work.

```
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
  /Users/trantorliu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect'
  /Users/trantorliu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
  /Users/trantorliu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
  /Users/trantorliu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect'
  /Users/trantorliu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
  /Users/trantorliu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:852:in `start'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/util/http_helper.rb:68:in `block in http_call'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/util/http_helper.rb:93:in `log_http_call'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/rest.rb:158:in `log_http_call'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/util/http_helper.rb:66:in `http_call'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/rest.rb:61:in `token_hash'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/rest.rb:74:in `token_type'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/rest.rb:127:in `format_request'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/base.rb:83:in `api_call'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/rest.rb:95:in `api_call'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/core/api/base.rb:96:in `post'
  paypal-sdk-rest (1.1.0) lib/paypal-sdk/rest/data_types.rb:60:in `create'
```

Here's my code:
```ruby
payment = PayPal::SDK::REST::Payment.new({
          :intent => "sale",
          :redirect_urls => {
            :return_url => return_url,
            :cancel_url => cancel_url },
          :payer => {
            :payment_method => "paypal" },
          :transactions => [{
            :item_list => {
              :items => [{
                :name => "$#{credit} Credit",
                :description => "$#{credit} for $#{money}.",
                :price => money,
                :currency => "USD",
                :quantity => 1 }]},
            :amount => {
              :total => money,
              :currency => "USD" },
            :description => "$#{credit} prepaid credit." }]})

```

**Comment by jhilden** [comment]
we seem to be having the same issue upgrading from paypal-sdk-rest `0.7.2` to `1.x` :(

**Comment by jhilden** [comment]
the issue seems to be that the `paypal.crt` has not been packaged in recent versions of the gem as described in #86  Using the fork from this PR `gem 'paypal-sdk-rest', github: 'johnkolen/PayPal-Ruby-SDK', ref: '59c881d96936b443690f5cbfbcca5accd7d700be'` solved the ssl verficiation for us.

@paypal Please release a fix for this critical bug as soon as possible

**Comment by trantorLiu** [comment]
@jhilden Thank you so much! But finally I solved the problem by downloading the `data/paypal.crt` to my `config` dir, and specifying it in my `config/paypal.yml` like this:
```yml
ca_file: <%= File.expand_path("#{__dir__}/paypal.crt") %>
```

**Comment by juwlee** [comment]
@jhilden @trantorLiu a new version with the fix from #86 has been released. Please try it out and let us know if it persists.

**Comment by trantorLiu** [comment]
@juwlee Thank you!

**Comment by jhilden** [comment]
a bit late to the party, but still thanks a lot for fixing this so quickly.
